openapi: 3.0.0
info:
  title: Delta App API
  version: 1.0.0
  description: API documentation for the Delta App

servers:
  - url: http://localhost:8000/api/v1

paths:
  /users/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful

  /users/register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                avatar:
                  type: string
                  format: binary
                coverImage:
                  type: string
                  format: binary
      responses:
        '201':
          description: Registration successful
